import {Skill} from './skill.model';

export const skills: Skill[] = [
  { icon: 'assets/selfboom.png', description: 'On death, 25% chance to explode', score: 50000 },
  { icon: 'assets/skill_guild_gongjihuixue.png', description: 'After every 6 attacks, the next attacks restores 1%-10% of Max HP', score: 49000 },
  { icon: 'assets/skill_guild_xuelianghuifu30.png', description: 'When dying, 50% chance to restore 30% of HP (Once per match)', score: 48000 },
  { icon: 'assets/skill_guild_fenshen.png', description: '25% chance on start to summon 1 clone (with 50% ATk and 50% HP)', score: 47000 },
  { icon: 'assets/skill_guild_wudi2s.png', description: 'After taking damage, 60% chance to be invincible for 2s and blocks piercing projectiles', score: 46000 },
  { icon: 'assets/skill_guild_baojijianshang+10.png', description: 'CRIT DMG REDUC+10%', score: 45000 },
  { icon: 'assets/skill_guild_shanbi+5.png', description: 'Dodge+5%', score: 44000 },
  { icon: 'assets/skill_guild_jianshang+5.png', description: 'DMG REDUC+5%', score: 43000 },
  { icon: 'assets/skill_guild_shengming+1000.png', description: 'Max HP+10%', score: 42000 },
  { icon: 'assets/skill_guild_gongji+100.png', description: 'ATK PWR+10%', score: 41000 },
  { icon: 'assets/selfboom.png', description: 'On death, 20% chance to explode', score: 40000 },
  { icon: 'assets/skill_guild_gongjihuixue.png', description: 'After every 7 attacks, the next attacks restores 1%-10% of Max HP', score: 39000 },
  { icon: 'assets/skill_guild_xuelianghuifu30.png', description: 'When dying, 40% chance to restore 30% of HP (Once per match)', score: 38000 },
  { icon: 'assets/skill_guild_fenshen.png', description: '20% chance on start to summon 1 clone (with 50% ATk and 50% HP)', score: 37000 },
  { icon: 'assets/skill_guild_wudi2s.png', description: 'After taking damage, 50% chance to be invincible for 2s and blocks piercing projectiles', score: 36000 },
  { icon: 'assets/skill_guild_baojijianshang+10.png', description: 'CRIT DMG REDUC+10%', score: 35000 },
  { icon: 'assets/skill_guild_shanbi+5.png', description: 'Dodge+5%', score: 34000 },
  { icon: 'assets/skill_guild_jianshang+5.png', description: 'DMG REDUC+5%', score: 33000 },
  { icon: 'assets/skill_guild_shengming+1000.png', description: 'Max HP+10%', score: 32000 },
  { icon: 'assets/skill_guild_gongji+100.png', description: 'ATK PWR+10%', score: 31000 },
  { icon: 'assets/selfboom.png', description: 'On death, 15% chance to explode', score: 30000 },
  { icon: 'assets/skill_guild_gongjihuixue.png', description: 'After every 8 attacks, the next attacks restores 1%-10% of Max HP', score: 29000 },
  { icon: 'assets/skill_guild_xuelianghuifu30.png', description: 'When dying, 30% chance to restore 30% of HP (Once per match)', score: 28000 },
  { icon: 'assets/skill_guild_fenshen.png', description: '15% chance on start to summon 1 clone (with 50% ATk and 50% HP)', score: 27000 },
  { icon: 'assets/skill_guild_wudi2s.png', description: 'After taking damage, 40% chance to be invincible for 2s and blocks piercing projectiles', score: 26000 },
  { icon: 'assets/skill_guild_baojijianshang+10.png', description: 'CRIT DMG REDUC+10%', score: 25000 },
  { icon: 'assets/skill_guild_shanbi+5.png', description: 'Dodge+5%', score: 24000 },
  { icon: 'assets/skill_guild_jianshang+5.png', description: 'DMG REDUC+5%', score: 23000 },
  { icon: 'assets/skill_guild_shengming+1000.png', description: 'Max HP+10%', score: 22000 },
  { icon: 'assets/skill_guild_gongji+100.png', description: 'ATK PWR+10%', score: 21000 },
  { icon: 'assets/selfboom.png', description: 'On death, 10% chance to explode', score: 20000 },
  { icon: 'assets/skill_guild_gongjihuixue.png', description: 'After every 9 attacks, the next attacks restores 1%-10% of Max HP', score: 19000 },
  { icon: 'assets/skill_guild_xuelianghuifu30.png', description: 'When dying, 20% chance to restore 30% of HP (Once per match)', score: 18000 },
  { icon: 'assets/skill_guild_fenshen.png', description: '10% chance on start to summon 1 clone (with 50% ATk and 50% HP)', score: 17000 },
  { icon: 'assets/skill_guild_wudi2s.png', description: 'After taking damage, 30% chance to be invincible for 2s and blocks piercing projectiles', score: 16000 },
  { icon: 'assets/skill_guild_baojijianshang+10.png', description: 'CRIT DMG REDUC+10%', score: 15000 },
  { icon: 'assets/skill_guild_shanbi+5.png', description: 'Dodge+5%', score: 14000 },
  { icon: 'assets/skill_guild_jianshang+5.png', description: 'DMG REDUC+5%', score: 13000 },
  { icon: 'assets/skill_guild_shengming+1000.png', description: 'Max HP+10%', score: 12000 },
  { icon: 'assets/skill_guild_gongji+100.png', description: 'ATK PWR+10%', score: 11000 },
  { icon: 'assets/selfboom.png', description: 'On death, 5% chance to explode', score: 10000 },
  { icon: 'assets/skill_guild_gongjihuixue.png', description: 'After every 10 attacks, the next attacks restores 1%-10% of Max HP', score: 9000 },
  { icon: 'assets/skill_guild_xuelianghuifu30.png', description: 'When dying, 10% chance to restore 30% of HP (Once per match)', score: 8000 },
  { icon: 'assets/skill_guild_fenshen.png', description: '5% chance on start to summon 1 clone (with 50% ATk and 50% HP)', score: 7000 },
  { icon: 'assets/skill_guild_wudi2s.png', description: 'After taking damage, 20% chance to be invincible for 2s and blocks piercing projectiles', score: 6000 },
  { icon: 'assets/skill_guild_baojijianshang+10.png', description: 'CRIT DMG REDUC+10%', score: 5000 },
  { icon: 'assets/skill_guild_shanbi+5.png', description: 'Dodge+5%', score: 4000 },
  { icon: 'assets/skill_guild_jianshang+5.png', description: 'DMG REDUC+5%', score: 3000 },
  { icon: 'assets/skill_guild_shengming+1000.png', description: 'Max HP+10%', score: 2000 },
  { icon: 'assets/skill_guild_gongji+100.png', description: 'ATK PWR+10%', score: 1000 }
];
